<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE marcadores [
<!ELEMENT marcadores (marcador)+>
<!ELEMENT marcador (nombre, url)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT url (#PCDATA)>
]>
<marcadores>
<marcador>
<nombre>W3C</nombre>
<url>http://www.w3.org</url>
</marcador>
<marcador>
<nombre>Web Hypertext Application Technology Working Group</nombre>
<url>http://www.whatwg.org</url>
</marcador>
</marcadores>